name: Build and Test App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  security:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the rpository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Intall the dependencies
      run: npm install

    - name: Build the application
      run: npm run build --if-present

    - name: Unit test
      run: npm audit


  build_test:

    runs-on: ubuntu-latest
    needs: security

    steps:
    - name: Checkout the rpository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Intall the dependencies
      run: npm install

    - name: Build the application
      run: npm run build --if-present

    - name: Unit test
      run: npm test
